### PR TITLE
Newly created PR: Initiatedragonmove mousedown propagation <2>

### PR DESCRIPTION
**Pull request by victorroeder**
Hello John,

did another small correction for ticket #47 so that the mouse event is not propagated when target is a GWT Label based widget.

Now within the master branch.

My git(hub) skills increase step by step :-).

Victor

### CODE REVIEW

**Comment by victorroeder** [comment]
> The Element.is() check done at 217 should probably be moved here?

Sorry for late reply... Was the question addressed to me, or did you just think in words?
If addressed to: Yes go ahead!

Victor

**Comment by johndevs** [comment]
@victorroeder Sorry for the confusion, I was in a hurry and just wanted to put my thoughts down when I looked at the fix. I'm not sure Github will allow me to make the changes to the PR, only the author can do it, so if you have time would you mind making the changes?

Thanks again for the PR!

**Comment by victorroeder** [comment]
Hello John, sorry but it seems I confused you and myself a little bit :-). Now I think I understood what you meant with your line notes. The short answer is: It is already like you suggested. The interesting commit is the last/fourth one (7f6c06b).

The long answer:
When I made my first contribution (for ticket #13, first commit: 18762da), you did some code clean-up afterwards, which I merged into my forked Repository in return (which created 2nd and 3rd commit: e3a0239 and 2f75f07).
You wrote now some comments to my very first commit (18762da), but you already did it during your clean-up (which I merged with commits e3a0239 and 2f75f07).

Then I did the actual correction for ticket #47 (see 4th commit 7f6c06b). And that's the one that is actually interesting.

I hope this was understandable. Sorry for confusion! (and I really really have to get to know github better ... :-(  ).

With kind regards and happy Eastern!
Victor

**Comment by johndevs** [comment]
@victorroeder Thanks for fixing these up :+1: 

I've now merged the PR and it will be included in the next release.

Happy eastern!

**Pull request merged**
