### PR TITLE
Close button on VDDTabsheet tab caption should not be draggable due to problems with touch devices #59

### PR DESCRIPTION
**Pull request by jreznot**
Commit fixes close button of TabSheet tabs on touch screens

### CODE REVIEW

**Comment by jreznot** [comment]
Also please fix build of project, it fails with new vaadin plugin. And I can't use
> gradle clean install
to test addon

**Comment by johndevs** [comment]
Build should work now, if you re-base the change on top of master branch

**Comment by jreznot** [comment]
Hi, my changes are on top of master branch. You can merge them.
Also Travis CI widget shows build:error on master of your repo.

**Comment by jreznot** [comment]
It seems that Travis CI uses default Vaadin version 7.6.0.beta1 (specified in build.gradle) that does not exists in repositories

**Pull request merged**
